development:
  adapter: postgresql
  encoding: utf8
  username: user3
  password: alexxxone89
  database: blog15_development
test:
  adapter: postgresql
  encoding: utf8
  username: user3
  password: alexxxone89
  database: blog15_test

production:
  adapter: postgresql
  encoding: utf8
  username: user3
  password: alexxxone89
  database: blog15_production
